#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  # service::config_set SERVICE_MINIO_PORT text "Port" 9000
  # service::config_set SERVICE_MINIO_CONSOLE_PORT text "Console Port" 9001

  service::config_set SERVICE_MINIO_USERNAME text "Username"
  service::config_set SERVICE_MINIO_PASSWORD text "Password"
}

check $@
